// Created with the help of an AI Agent and littlespidy.
package com.littlespidy.responseinspector.engine;

import burp.api.montoya.http.message.HttpRequestResponse;
import burp.api.montoya.http.message.responses.HttpResponse;
import com.littlespidy.responseinspector.model.FindingCategory;
import com.littlespidy.responseinspector.model.FindingEntry;
import com.littlespidy.responseinspector.model.InspectorDataStore;

import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Scans HTTP responses for detailed error messages and stack traces leaked by:
 * - Web Servers (Apache, Nginx, JBoss, Waitress, WebSEAL)
 * - ASP.NET (.NET exceptions, OLE DB, C# stack traces)
 * - Databases (MySQL, PostgreSQL, Oracle, MSSQL, SQLite, DB2, MongoDB, LDAP)
 * - Runtimes & Frameworks (PHP, Java, Python, Ruby, Go, Node.js, Django, Hibernate)
 *
 * Patterns ported directly from DetectHTTPResponseErrors_littlespidy.bambda.
 */
public class ErrorScanner {

    private record ErrorRule(String categoryName, List<String> literals, List<Pattern> regexes) {}

    private final List<ErrorRule> rules = new ArrayList<>();

    public ErrorScanner() {
        initRules();
    }

    private void initRules() {
        // Apache Server
        rules.add(new ErrorRule("Apache Server Error",
                List.of("Apache Server at"),
                List.of(Pattern.compile("AH[0-9]{5}:"), Pattern.compile("mod_[\\w]+:"))));

        // NGINX Server
        rules.add(new ErrorRule("NGINX Server Error",
                List.of("client intended to address", "could not build optimal proxy_headers_hash"),
                Collections.emptyList()));

        // JBoss / WildFly
        rules.add(new ErrorRule("JBoss / WildFly Error",
                Collections.emptyList(),
                List.of(Pattern.compile("JBWEB[0-9]{6}:"), Pattern.compile("WFLY[A-Z0-9]+:"))));

        // Waitress Python Server
        rules.add(new ErrorRule("Waitress Python Server Error",
                List.of("(generated by waitress)"),
                Collections.emptyList()));

        // WebSEAL
        rules.add(new ErrorRule("WebSEAL Error",
                List.of("websealerror"),
                List.of(Pattern.compile("(132120c8|38ad52fa|38cf013d|38cf0259|38cf025a|38cf025b|38cf0421|38cf07aa)"))));

        // ASP.NET / IIS
        rules.add(new ErrorRule("ASP.NET Exception / Stack Trace",
                List.of("Exception of type", "--- End of inner exception stack trace ---",
                        "Microsoft OLE DB Provider", "\"Message\":\"Invalid web service call",
                        "Syntax error in string in query expression", "Server Error in '/' Application",
                        "ASP.NET is configured to show verbose error messages"),
                List.of(Pattern.compile("System\\.([A-Za-z]{1,32}\\.)*[A-Za-z]{0,32}Exception:"),
                        Pattern.compile("in [A-Za-z]:\\\\([A-Za-z0-9_]+\\\\)+[A-Za-z0-9_\\-]+(\\.aspx)?\\.cs:line [\\d]+"),
                        Pattern.compile("Error ([\\d-]+) \\([\\dA-Fa-f]+\\)"),
                        Pattern.compile("\\bat ([a-zA-Z0-9_]*\\.)*([a-zA-Z0-9_]+)\\([a-zA-Z0-9, \\[\\]&;]*\\)"))));

        // MySQL / MariaDB
        rules.add(new ErrorRule("MySQL / MariaDB Error",
                List.of("You have an error in your SQL syntax; check the manual that corresponds to your MySQL",
                        "check the manual that corresponds to your MariaDB",
                        "Error: Unknown column", "valid MySQL result", "MySqlClient.",
                        "com.mysql.jdbc.exceptions", "1062 Duplicate entry", "mysql_fetch",
                        "mysql_num_rows", "mysql_query", "MySqlException"),
                List.of(Pattern.compile("Illegal mix of collations \\([\\w\\s,]+\\) and \\([\\w\\s,]+\\) for operation"),
                        Pattern.compile("Warning.*mysql_"),
                        Pattern.compile("SQL syntax.*MySQL"))));

        // PostgreSQL
        rules.add(new ErrorRule("PostgreSQL Error",
                List.of("pg_query", "pg_exec", "PSQLException", "valid PostgreSQL result",
                        "Npgsql.", "org.postgresql.util.PSQLException", "unterminated quoted string at or near"),
                List.of(Pattern.compile("PostgreSQL.*ERROR"),
                        Pattern.compile("Warning.*\\Wpg_"),
                        Pattern.compile("ERROR:\\s+syntax error at or near"))));

        // Oracle DB
        rules.add(new ErrorRule("Oracle DB Error",
                List.of("Oracle error", "quoted string not properly terminated", "Warning: oci_parse()", "oracleException"),
                List.of(Pattern.compile("\\bORA-[0-9]{5}\\b"),
                        Pattern.compile("Oracle.*Driver\\]"),
                        Pattern.compile("Warning.*\\Woci_"),
                        Pattern.compile("Warning.*\\Wora_"))));

        // Microsoft SQL Server
        rules.add(new ErrorRule("Microsoft SQL Server Error",
                List.of("Unclosed quotation mark", "Conversion failed when converting the",
                        "Microsoft SQL Native Client", "ODBC SQL Server Driver", "SqlException",
                        "SqlClient.", "mssql_query", "Incorrect syntax near"),
                List.of(Pattern.compile("\\[(ODBC SQL Server Driver|SQL Server|ODBC Driver Manager)\\]"),
                        Pattern.compile("warning.*mssql_"),
                        Pattern.compile("Driver.*SQL[-_]*Server"),
                        Pattern.compile("Msg \\d+, Level \\d+, State \\d+"))));

        // SQLite
        rules.add(new ErrorRule("SQLite Error",
                List.of("SQLite/JDBCDriver", "SQLite.Exception", "System.Data.SQLite.SQLiteException",
                        "[SQLITE_ERROR]", "SQLite3::", "SQLITE_ERROR", "sqlite_query", "SQLiteException"),
                List.of(Pattern.compile("Warning.*sqlite_"),
                        Pattern.compile("near \".*\": syntax error"))));

        // IBM DB2
        rules.add(new ErrorRule("IBM DB2 Error",
                List.of("DB2 SQL error", "com.ibm.db2"),
                List.of(Pattern.compile("CLI Driver.*DB2"),
                        Pattern.compile("db2_\\w+\\("),
                        Pattern.compile("SQLCODE=-\\d+"))));

        // MongoDB
        rules.add(new ErrorRule("MongoDB Error",
                List.of("uncaught exception:", "MongoServerError", "MongoError", "org.mongodb.driver"),
                List.of(Pattern.compile("E QUERY\\s+\\[thread1\\] SyntaxError:"))));

        // LDAP Leak
        rules.add(new ErrorRule("LDAP Leakage",
                List.of("javax.naming.NameNotFoundException", "LDAP: error code"),
                List.of(Pattern.compile("((dn|dc|cn|ou|uid|o|c)=[\\w\\d]*,\\s?){2,}"))));

        // PHP
        rules.add(new ErrorRule("PHP Error / Stack Trace",
                List.of("Fatal error:", "Call to undefined function"),
                List.of(Pattern.compile("\\.php on line [0-9]+"),
                        Pattern.compile("\\.php</b> on line <b>[0-9]+"),
                        Pattern.compile("Undefined (index|variable|offset):"),
                        Pattern.compile("Fatal error:.*in /.*\\.php.*line \\d+"),
                        Pattern.compile("Warning:.*in /.*\\.php.*line \\d+"),
                        Pattern.compile("Parse error:.*in /.*\\.php.*line \\d+"))));

        // Java
        rules.add(new ErrorRule("Java Exception / Stack Trace",
                List.of(".invoke(Unknown Source)", "nested exception is", "java.io.FileNotFoundException:", "Exception in thread"),
                List.of(Pattern.compile("\\.java:[0-9]+"),
                        Pattern.compile("java\\.lang\\.([A-Za-z0-9_]*)Exception"),
                        Pattern.compile("\\bat [a-zA-Z][a-zA-Z0-9_.]*\\.[a-zA-Z][a-zA-Z0-9_]*\\([^)]*\\.java:\\d+\\)"),
                        Pattern.compile("(?:Exception|Error):\\s+.*\\n\\s*at .*"))));

        // Python
        rules.add(new ErrorRule("Python Traceback / Error",
                List.of("Traceback (most recent call last):", "NameError:", "ImportError:", "IndentationError:"),
                List.of(Pattern.compile("File \"[A-Za-z0-9\\-_./]*\", line [0-9]+, in"))));

        // Ruby
        rules.add(new ErrorRule("Ruby / Rails Error",
                List.of("ActiveRecord::StatementInvalid", "ActiveRecord::RecordNotFound", "(backtrace)", "ActionView::Template::Error"),
                List.of(Pattern.compile("\\.rb:[0-9]+:in"),
                        Pattern.compile("from /[^ ]+\\.rb:\\d+:in `.*'"))));

        // Node.js / JavaScript
        rules.add(new ErrorRule("Node.js / JavaScript Error",
                List.of("ReferenceError:", "TypeError:", "UnhandledPromiseRejectionWarning:"),
                List.of(Pattern.compile("\\.js:[0-9]+:[0-9]+"),
                        Pattern.compile("Error:.*\\n\\s*at .* \\([^)]*:\\d+:\\d+\\)"))));

        // Go panic
        rules.add(new ErrorRule("Go Panic / Stack Trace",
                List.of("panic: runtime error:"),
                List.of(Pattern.compile("goroutine \\d+ \\[.*\\]:"),
                        Pattern.compile("panic:.*\\n\\s*goroutine \\d+"))));

        // Frameworks: Django & Hibernate
        rules.add(new ErrorRule("Django ORM Error",
                List.of("django.db.utils.", "ProgrammingError at"),
                Collections.emptyList()));
        rules.add(new ErrorRule("Hibernate / JPA Error",
                List.of("HibernateException", "QuerySyntaxException", "org.hibernate.exception"),
                Collections.emptyList()));
    }

    public List<FindingEntry> scan(HttpRequestResponse requestResponse, InspectorDataStore dataStore) {
        List<FindingEntry> findings = new ArrayList<>();
        if (requestResponse == null || requestResponse.response() == null) {
            return findings;
        }

        HttpResponse response = requestResponse.response();
        String body = ScannerUtils.convertByteArrayToString(response.body());
        if (body.isEmpty()) {
            return findings;
        }

        for (ErrorRule rule : rules) {
            boolean matched = false;
            String snippet = "";
            int matchStart = -1;
            int matchEnd = -1;

            // Check string literals first (fastest)
            for (String literal : rule.literals) {
                int idx = body.indexOf(literal);
                if (idx != -1) {
                    matched = true;
                    matchStart = idx;
                    matchEnd = idx + literal.length();
                    int start = Math.max(0, idx - 20);
                    int end = Math.min(body.length(), idx + literal.length() + 40);
                    snippet = body.substring(start, end).replaceAll("[\\r\\n]+", " ");
                    break;
                }
            }

            // Check regexes if literal didn't match
            if (!matched) {
                for (Pattern p : rule.regexes) {
                    Matcher m = p.matcher(body);
                    if (m.find()) {
                        matched = true;
                        matchStart = m.start();
                        matchEnd = m.end();
                        int start = Math.max(0, m.start() - 20);
                        int end = Math.min(body.length(), m.end() + 40);
                        snippet = body.substring(start, end).replaceAll("[\\r\\n]+", " ");
                        break;
                    }
                }
            }

            if (matched) {
                findings.add(FindingEntry.create(
                        dataStore.nextId(),
                        FindingCategory.ERROR,
                        rule.categoryName,
                        snippet.trim(),
                        "Response Body",
                        requestResponse,
                        matchStart,
                        matchEnd
                ));
            }
        }

        return findings;
    }
}
